### PR TITLE
Bugfix user.model: skip & limit cast to number

### PR DESCRIPTION
**Pull request by osahner**
Small fix with Test

### CODE REVIEW

**Comment by osahner** [comment]
Are there any problems with this pr? It's just a small fix, even with a Test case.

**Comment by rcaracaus** [comment]
Limit is unusable without this fix

**Comment by KunalKapadia** [comment]
@osahner Apologise for the delay. Merging now.

**Comment by KunalKapadia** [comment]
@rcaracaus Just FYI, this is merged now.

**Pull request merged**
