### PR TITLE
Update node, remove gulp and babel 

### PR DESCRIPTION
**Pull request by kunalkapadia**

### CODE REVIEW

**Comment by osahner** [comment]
This pr looks promising.

**Comment by osahner** [comment]
Please merge or better branch this PR.

**Comment by okonon** [comment]
@KunalKapadia could you please merge this PR?

**Comment by nckenn** [comment]
can you make a release version of this?

**Comment by kunalkapadia** [comment]
Hey @osahner @okonon @nckenn. Haven't been able to devote time to this project since quite some time. I am going through each of the PRs and issues now. Also created a [release](https://github.com/kunalkapadia/express-mongoose-es6-rest-api/tree/v5.0.0) for this PR

**Pull request merged**
