### PR TITLE
dokku deployment workflow

### PR DESCRIPTION
**Pull request by zombler**
assumes a pre-existing dokku setup: could elaborate to cover a fresh install. 
the gulp tasks should be improved: would appreciate any feedback!

### CODE REVIEW

**Comment by KunalKapadia** [comment]
Also can you replace `gulp-clean` with `del` npm package as `gulp-clean` has been deprecated.

**Comment by zombler** [comment]
ah yes, the reason for the `npm start` change is because when our dokku machine runs gulp serve it results in an error (only the contents of `dist` are pushed to dokku). i'm aware this isn't ideal, and will look into a work around

**Comment by KunalKapadia** [comment]
We generally use `gulp serve` for development purpose only. When we host our code in a VM, we use [pm2](https://github.com/Unitech/pm2) to start our service like `pm2 start index.js`. pm2 has lots of useful features, one of the most important being it can start service even if VM is rebooted.

**Comment by KunalKapadia** [comment]
@zombler Please let me know if you need any help.

**Pull request closed without merging**
