### PR TITLE
Param validation in controllers and routes folders

### PR DESCRIPTION
**Pull request by ravindrabhakta07**
I have moved paramValidation from param-validation.js file to the routes for more code readability and maintainability. And also moved routes to sub-folder apiRoutes so that we can later add webRoutes in the same folder

### CODE REVIEW

**Comment by ravindrabhakta07** [comment]
Have changed the environment configurations in reference to issue #98 .

**Comment by KunalKapadia** [comment]
@ravindrabhakta07 Param validation should be in separate file altogether.
Also it'd be great if we can discuss changes/features required before sending a PR.

**Comment by ravindrabhakta07** [comment]
@KunalKapadia "Param validation should be in separate file altogether." - The file will grow in a massive file when the system is large. It's better to split the validation of params in the same file where they are used (in routes). If we have change in a parameter, hen we can directly change the validation of that param in same file.

Also I have changed the environment configuration. What are your comments on that.
Sure we can discuss the changes/features that are required. Please let me know.

**Comment by KunalKapadia** [comment]
@ravindrabhakta07 The point of keeping them in same file is to have validations in one place. Also there will be long rules which will be shared by various validations in different routes.

Also we'll be moving towards using `node-config` package for handling env variables.

**Comment by simonschllng** [comment]
I also disliked this part of the setup. As @ravindrabhakta07 said, the file will get huge. And the position in `config/env` is strange to me as well. @KunalKapadia also has a point about the code sharing. But the structure as it is atm. does not reflect that and doesn't encourage to share code as it maps 1:1 to api methods.

I will move it and break it down to smaller parts in my project. One file per model and one _common-validators_ for the rest. Or maybe remove it completely and use mongoose validators only.

**Comment by ouzhou** [comment]
i agree @simonschllng 
when the file is too huge, it's very hard to maintain

**Pull request closed without merging**
